#!/usr/bin/env bash

# =======================================
# @auther : parkjunhong77@gmail.com
# @title  : git merge from A to B
# @license: Apache License 2.0
# @since  : 2020-08-18
# =======================================

help(){
	
	if [ $# -gt 0 ];then
		echo
		echo "['${FUNCNAME[1]}' says] " $1
	fi
    echo
    echo "[Usage]"
    echo "git-merge.sh -s <source> -t <target>"
    echo
    echo "[Arguments]"
    echo " -s | --source: a source branch. If not set, search automatically. Just select !"
    echo " -t | --target: a target branch. If not set, search automatically. Just select !"
}

SOURCE=""
TARGET=""

while [ "$1" != "" ];
do
    case $1 in
        -s | --source)
            shift
            SOURCE="$1"
            ;;
        -t | --target)
            shift
            TARGET="$1"
            ;;
        -h | --help)
            help
            exit 0
            ;;
        *)
            ;;
    esac
    shift
done

# Read current branches.
read-branches(){
	local _branches=()
	uuid=$(uuidgen)
	while read -r branch
	do
		if [[ "$branch" == \** ]];then
			_branches+=(${branch:2})
		elif [ "$branch" = "$uuid" ];then
			_branches=()
			break
		else
			_branches+=($branch)
		fi
	done <<< $(git branch 2>/dev/null || echo $uuid)

	echo "${_branches[@]}"
}

# Show branches.
show-branches(){
	echo
	echo "* Current branches"
	for idx in "${!BRANCHES[@]}";
	do
		((idx=idx+1))
		printf " [%2s] %s\n" $idx "${BRANCHES[$idx-1]}"
	done
	echo
}

# Select a branch.
# $1 {string}: title or purpose.
select-branch(){
	read -p "Select '$1' branch [1 ~ ${#BRANCHES[@]}]: " index
	re="^[0-9]+$"
	if [ -z "$index" ] || ! [[ $index =~ $re ]] || [ $index -gt ${#BRANCHES[@]} ] || [ $index -lt 1 ]; then
		index=$(date +%s)
	fi
	echo ${BRANCHES[$index-1]}
}

# @param $1 {string}: a name of an array
# @param $2 {any}: value
# @return 0 means no, 1 yes
has-value(){
	c=0
	ar="\${$1[@]}"
	for v in $(eval "echo ${ar}");
	do
		if [ "$v" == "$2" ];then
			c=1
			break
		fi
	done

	echo $c
}

# @param $1 {string} branch type. [source|target]
assign-branch(){
	show-branches
	local branch=$(select-branch "$1")

	if [ -z "$branch" ];then
		echo
		echo "[ERROR] * * * The selected 'source' branch is invalid, empty"
		help	
		exit 1
	fi
	
	if [ "$1" == "source" ];then
		SOURCE="$branch"
	elif [ "$1" == "target" ];then
		TARGET="$branch"
	fi
}

BRANCHES=($(read-branches))
if [ ${#BRANCHES[@]} -lt 1 ];then
	echo "[ERROR] * * * (A current or one of above folders) is not a git repository."
	help
	exit 1
fi

CUR_BRANCH=$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')

if [ -z "$SOURCE" ] && [ -z "$TARGET" ];then
	assign-branch "source"
	assign-branch "target"
elif [ -z "$SOURCE" ];then
	SOURCE="$CUR_BRANCH"
elif [ -z "$TARGET" ];then
	TARGET="$CUR_BRANCH"
fi

# check source and target
_branches=( $SOURCE $TARGET )
for _branch in ${_branches[@]};
do
	if [ $(has-value "BRANCHES" "$_branch") -lt 1 ];then
		echo
		echo "*** branch('$_branch') DOES NOT exists."
		help
		exit 1
	fi 
done

if [ "$SOURCE" == "$TARGET" ];then
	echo
	echo "[ERROR] * * * Invalid a source and a target branches. source (=) target."
	help
	exit 1
fi

# 1. update from 'remote' of 'source' branch
echo
echo " > > > git checkout \"${SOURCE}\""
git checkout "${SOURCE}"
git pull

# 2. update from 'remote' of 'target' branch
echo
echo " > > > git checkout \"${TARGET}\""
git checkout "${TARGET}"
git pull

# 3. merge from 'source' to 'target'
echo
echo " > > > git merge \"${SOURCE}\""
git merge "${SOURCE}"

# 4. push to 'remote' of 'target'
echo
echo " > > > git push"
git push

# 5. come back to 'current'
echo 
echo " > > > git checkout \"${CUR_BRANCH}\""
git checkout "${CUR_BRANCH}"

exit 0


