#!/bin/bash

# =======================================
# @auther : parkjunhong77@gmail.com
# @title  : git merge from A to B
# @license: Apache License 2.0
# @since  : 2020-08-18
# =======================================

help(){
    echo
    echo "[Usage]"
    echo "git-merge.sh -s <source> -t <target>"
    echo
    echo "[Arguments]"
    echo " -s | --source: a source branch. If not set, search automatically."
    echo " -t | --target: a target branch"
}

SOURCE=""
TARGET=""

while [ "$1" != "" ];
do
    case $1 in
        -s | --source)
            shift
            SOURCE="$1"
            ;;
        -t | --target)
            shift
            TARGET="$1"
            ;;
        -h | --help)
            help
            exit 0
            ;;
        *)
            ;;
    esac
    shift
done

if [ -z "${SOURCE}" ];
then
    uuid=$(uuidgen)
    while read -r branch
    do
        if [[ "${branch}" == \** ]];
        then
            SOURCE=${branch:2}
        elif [ "${branch}" = "${uuid}" ];
        then
            echo
            echo "[ERROR] * * * (A current or one of above folders) is not a git repository."
            help
            exit 1
        fi
    done <<< $(git branch 2>/dev/null || echo ${uuid})
fi

if [ -z "${SOURCE}" ] || [ -z "${TARGET}" ];
then
    echo
    echo "[ERRROR] * * * Invalid merge branches. source=${SOURCE}, target=${TARGET}"    
    help
    exit 1
fi

echo
echo " > > > git checkout \"${TARGET}\""
git checkout "${TARGET}"

echo
echo " > > > git merge \"${SOURCE}\""
git merge "${SOURCE}"

echo
echo " > > > git push"
git push

echo 
echo " > > > git checkout \"${SOURCE}\""
git checkout "${SOURCE}"

exit 0


