#!/bin/bash

# Describe: check a memory usage of Java Processes."
# Author: parkjunohng77@gmail.com
# License: MIT License.

TARGET="TARGET"
LOG_DIR="$HOME/directory"
LOG_FILE="memory-usage-"$(date "+%Y%m%d")".log"
TIME=$(date "+%Y-%m-%d %H:%M:%S")

if [ ! -d ${LOG_DIR} ];
then
    mkdir ${LOG_DIR}
fi

CMD="ps -o pid,user,%mem,command ax | grep [j]ava | grep ${TARGET} | grep [-]Dname | grep -v watch | sort -b -k3 -r"
while IFS=" " read -a _mem_usg_
do
    pid=${_mem_usg_[0]}
    user=${_mem_usg_[1]}
    usage=${_mem_usg_[2]}
    app=$(cut -d"=" -f2 <<< "${_mem_usg_[5]}")

    echo "${TIME}   ${usage}" >> ${LOG_DIR}/${app}-${pid}-${LOG_FILE}

done <<< "$(eval ${CMD})"

exit 0
