# `sudo` 로 실행시 '비밀번호'를 물어보지 않는 명령어
# 콤마(,)로 구분
#NO_PASSWORD_COMMANDS=

# '설치되어 있다면 삭제할 도구'
# 콤마(,)로 구분
# 
#REMOVE_PACKAGES=

# 기본 설치 도구.
# 콤마(,)로 구분
#INSTALL_PACKAGES=

# 사용자 정의 도구.
# `bash_completon`은 ${url_tool}.completion 
# 이름 패턴: URL_CUSTOM_TOOL.<식별정보>, <식별정보>에는 파일이름에 사용되는 문자 허용
URL_CUSTOM_TOOL.1=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/net/fwc-cli.sh
URL_CUSTOM_TOOL.2=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/sudo/sudoers-cli.sh

# 사용자 정의 설치 스크립트
# 이름 패턴: URL_CUSTOM_INSTALLER.<식별정보>, <식별정보>에는 파일이름에 사용되는 문자 허용
# 
#URL_CUSTOM_INSTALLER.1=

# RSA 기반의 ssh 접속을 위한 공개키.
# 이름 패턴: RSA_PUBLIC_KEY.<식별정보>, <식별정보>에는 파일이름에 사용되는 문자 허용
#RSA_PUBLIC_KEY.1=
