#!/usr/bin/env bash

# =======================================
# @auther : parkjunhong77@gmail.com
# @title  : build maven projects with user-custom 'profile' for build.
# @license: Apache License 2.0
# @since  : 2020-12-21
# @desc   : support macOS 11.2.3, Ubuntu 18.04, CentOS 7
# @completion: 
#
#
#
# =======================================


PROFILE=""
DEPLOY=0
TEST="true"
GIT_PULL="false"
while [ ! -z "$1" ];
do
	case "$1" in
		-p | --profile)
			shift
			PROFILE=$1
			;;
		-d)
			DEPLOY=1
			;;
		-u)
			GIT_PULL="true"
			;;
		-t | --test)
			TEST="false"
			;;
		*)
			;;
	esac
	shift
done

if [ -z $PROFILE ];
then
	echo
	echo "Require PROFILE"
	echo
	echo "./build-mvn-package -p <profile> -d"
	echo " -p: Profile"
	echo " -t: run Test"
	echo " -d: deploy after build."
	exit 1
fi

if [ "${GIT_PULL}" == "true" ];
then
	echo
	echo "git pull"
	git pull
fi

echo
echo " > mvn clean package -Dmaven.test.skip=${TEST} -Dbuild.profile=$PROFILE -U -up"
mvn clean package -Dmaven.test.skip=${TEST} -Dbuild.profile=$PROFILE -U -up

if [ $DEPLOY -ne 1 ];
then
	exit 0
fi

echo
echo " > cd ./deploy/$PROFILE"
cd ./deploy/$PROFILE
echo " > ./deploy.sh"
./deploy.sh
cd ..

exit 0
