#!/bin/bash

# ==============================================================================
# Script Name: migration-init-scheme.sh
# Description: Add 'DROP TABLE IF EXISTS' statement before 'CREATE TABLE'
# Author: Generated by AI
# ==============================================================================

# ------------------------------------------------------------------------------
# 1. Variables & Constants
# ------------------------------------------------------------------------------
SRC_SQL=""
INIT_SQL=""
FORCE_OVERWRITE=false

# 텍스트 컬러 (출력 가독성을 위해)
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ------------------------------------------------------------------------------
# 2. Helper Functions
# ------------------------------------------------------------------------------

usage() {
    echo -e "${BLUE}Usage:${NC} $0 [OPTIONS]"
    echo ""
    echo -e "${YELLOW}Options:${NC}"
    echo -e "  -s, --src-sql <file>       Input SQL file path (Required)"
    echo -e "  -i, --init-sql <file>      Output SQL file path (Required)"
    echo -e "  -f, --force-overwrite      Overwrite output file without prompting if it exists"
    echo -e "  -h, --help                 Show this help message"
    echo ""
    echo -e "${YELLOW}Example:${NC}"
    echo -e "  $0 -s original.sql -i migration.sql -f"
}

error_exit() {
    echo -e "${RED}Error: $1${NC}"
    exit 1
}

# ------------------------------------------------------------------------------
# 3. Parse Arguments
# ------------------------------------------------------------------------------

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -s|--src-sql) SRC_SQL="$2"; shift ;;
        -i|--init-sql) INIT_SQL="$2"; shift ;;
        -f|--force-overwrite) FORCE_OVERWRITE=true ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown parameter passed: $1"; usage; exit 1 ;;
    esac
    shift
done

# ------------------------------------------------------------------------------
# 4. Validation
# ------------------------------------------------------------------------------

# 1) 입력 파일 파라미터 확인
if [[ -z "$SRC_SQL" ]]; then
    error_exit "Input file is required. Use -s or --src-sql."
fi

# 2) 입력 파일 존재 여부 확인
if [[ ! -f "$SRC_SQL" ]]; then
    error_exit "Source file '$SRC_SQL' does not exist."
fi

# 3) 출력 파일 파라미터 확인
if [[ -z "$INIT_SQL" ]]; then
    error_exit "Output file is required. Use -i or --init-sql."
fi

# 4) 출력 파일 덮어쓰기 확인
if [[ -f "$INIT_SQL" ]]; then
    if [[ "$FORCE_OVERWRITE" == "true" ]]; then
        echo -e "${YELLOW}File '$INIT_SQL' exists. Overwriting due to --force-overwrite flag.${NC}"
    else
        echo -e -n "${YELLOW}File '$INIT_SQL' already exists. Overwrite? [Y/n] (default: Y): ${NC}"
        read -r response
        response=${response,,} # tolower
        
        if [[ "$response" =~ ^(no|n)$ ]]; then
            echo "Operation cancelled by user."
            exit 0
        fi
        echo "Overwriting file..."
    fi
fi

# ------------------------------------------------------------------------------
# 5. Execution (Processing File)
# ------------------------------------------------------------------------------

echo -e "${GREEN}Processing SQL file...${NC}"

# AWK를 사용하여 패턴 매칭 및 DROP 구문 삽입
# 로직: 
# 1. 라인이 "CREATE TABLE"로 시작하는지 확인
# 2. 맞다면 3번째 필드(테이블명)를 가져옴
# 3. 테이블명 뒤에 붙을 수 있는 '(' 문자를 제거
# 4. DROP 구문을 먼저 출력하고, 원래 라인을 출력

awk '{
    if ($0 ~ /^CREATE TABLE/) {
        tableName = $3
        gsub(/\(/, "", tableName)  # 테이블명 뒤의 ( 제거
        print "DROP TABLE IF EXISTS " tableName ";"
    }
    print $0
}' "$SRC_SQL" > "$INIT_SQL"

# ------------------------------------------------------------------------------
# 6. Finalize
# ------------------------------------------------------------------------------

if [[ $? -eq 0 ]]; then
    echo -e "${GREEN}Success! Migration SQL saved to: $INIT_SQL${NC}"
else
    error_exit "Failed to process the SQL file."
fi

