#!/usr/bin/env bash

# =======================================
# @auther : parkjunhong77@gmail.com
# @title  : copy lines as many as specified.
# @license: Apache License 2.0
# @since  : 2021-04-26
# @desc   : support macOS 11.2.3, Ubuntu 18.04, CentOS 7 or higher
# @completion: cplines.completion
#			 1. insert 'source <path>/cplines.completion" into ~/bin/.bashrc or ~/bin/.bash_profile for a personal usage.
