# `sudo` 로 실행시 '비밀번호'를 물어보지 않는 명령어
# 콤마(,)로 구분
NO_PASSWORD_COMMANDS=/usr/bin/cat, /usr/bin/firewalld, /usr/bin/firewall-cmd, /usr/bin/systemctl, /usr/bin/update-alternatives, /bin/ps, /bin/netstat, /usr/bin/watch, /usr/bin/file

# '설치되어 있다면 삭제할 도구'
# 콤마(,)로 구분
# 'ufw': 'firewalld / firewall-cmd'로 대체
REMOVE_PACKAGES=ufw

# 기본 설치 도구.
# 콤마(,)로 구분
INSTALL_PACKAGES=curl, git, net-tools, vim, jq, firewalld, file

# 사용자 정의 도구.
# `bash_completon`은 ${url_tool}.completion 
# 이름 패턴: URL_CUSTOM_TOOL.<식별정보>, <식별정보>에는 파일이름에 사용되는 문자 허용
URL_CUSTOM_TOOL.1=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/sys/vim-cli
URL_CUSTOM_TOOL.2=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/maven/build-mvn-package
URL_CUSTOM_TOOL.3=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/git/git-commit-push
URL_CUSTOM_TOOL.4=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/git/git-merge
URL_CUSTOM_TOOL.5=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/git/git-log-abbr
URL_CUSTOM_TOOL.6=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/build/deploy-profile
URL_CUSTOM_TOOL.7=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/net/fwc-cus.sh

# 사용자 정의 설치 스크립트
# 이름 패턴: URL_CUSTOM_INSTALLER.<식별정보>, <식별정보>에는 파일이름에 사용되는 문자 허용
# JDK 설치 스크립트
URL_CUSTOM_INSTALLER.1=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/java/install-temurin-25-jdk.sh
# 여러 버전의 JDK가 설치된 환경에서 '기본 버전'을 설정
URL_CUSTOM_INSTALLER.2=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/env/custom-installers/install-update-java-config.sh
# 'maven-3.9.15' 설치 스크립트
URL_CUSTOM_INSTALLER.3=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/env/custom-installers/install-maven-3.9.15.sh
# 여러 버전의 'maven' 이 설치된 환경에서 '기본 버전'을 설정
URL_CUSTOM_INSTALLER.4=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/env/custom-installers/install-update-mvn-config.sh

# RSA 기반의 ssh 접속을 위한 공개키.
# 이름 패턴: RSA_PUBLIC_KEY.<식별정보>, <식별정보>에는 파일이름에 사용되는 문자 허용
RSA_PUBLIC_KEY.1=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2mUlqLFWYVRfgyKT1+wmsY0Yr/wYEPs16zj1Cvy1/9o0ja7v4WQd+PM7Ha1qS4bDWI1TdtF8pwUmeJGR/UkQNS2tnzMCzdbpI9v7YbV+gR6btYaHLz6EThmNnR8qvXUb5muXBVb9Pf0lu4FfsjPnYZ4mEtMkiQrXUNKvFQEYpgZNewGmd+Mmbpj3LSWFOHGfbn5a+IlI2UemZnlvgTkrf+shGszwftiEeUmTo0El9tg5/LArK480HaWehTB+ndheUb/h05LtNP/oUA+8ZVkI7akEonKF/S+0o5BC6spOzP7iK4S+I7IUVIuoDWuhDLEV6xHYXH1cBEd3092x1YWkh ymtech for internal
