# `sudo` 로 실행시 '비밀번호'를 물어보지 않는 명령어
# 콤마(,)로 구분
#NO_PASSWORD_COMMANDS=

# '설치되어 있다면 삭제할 도구'
# 콤마(,)로 구분
#REMOVE_PACKAGES=

# 기본 설치 도구.
# 콤마(,)로 구분
#INSTALL_PACKAGES=

# 사용자 정의 도구.
# `bash_completon`은 ${url_tool}.completion 
# 이름 패턴: URL_CUSTOM_TOOL.<식별정보>, <식별정보>에는 파일이름에 사용되는 문자 허용
#URL_CUSTOM_TOOL.1=

# 사용자 정의 설치 스크립트
# 이름 패턴: URL_CUSTOM_INSTALLER.<식별정보>, <식별정보>에는 파일이름에 사용되는 문자 허용
#URL_CUSTOM_INSTALLER.1=

# 사용자 정의 실행 명령어
# 이름 패턴: URL_CUSTOM_COMMAND.<식별정보>, <식별정보>에는 파일이름에 사용되는 문자 허용.
#
#URL_CUSTOM_COMMAND.1=

# RSA 기반의 ssh 접속을 위한 공개키.
# 이름 패턴: RSA_PUBLIC_KEY.<식별정보>, <식별정보>에는 파일이름에 사용되는 문자 허용
RSA_PUBLIC_KEY.1=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdCDMAZjO6Y01xrM5dv0IGpBqFQkdMCIyBZ1EDffRhMxVOqo9aY/YM/dsRr64a8tA8qp0l9LCT+cZ2hMsJagDSnuVLusd3iDkR5NP2koFWZ0c7Ki7jStplyGRSS3se57TK0ERXpOh48oBwIzRchm6GcShVi9LqPZfcAvgZoiY2iUxiS0+HE35MlrvPnA7CkeXG6VDb4vxZ9pE4VcUvEZ6WVtUTSkjLHAHQt21qWMEvlRQ8xZqTe8DX/jirZbeWvH20OJeRsySSgI44gWTC6/0UFBwEPDmqXzu1uljG3MaLu42lJO4JUv9jx1ZSop1rVmU+6nHmF1uX6FABJ5PziN9d for Let's Encrypt
