#!/usr/bin/env bash

help(){
	if [ $# -gt 0 ];
	then
		echo
		echo "Call by $FUNCNAME[1]. message=$1"
	fi
	echo
	echo "Create a shell file to send a target server using 'ssh', 'scp' & 'sshpass'."
	echo 
	echo "Usage:"
	echo " scp-con-gen.sh -user <username> -pwd <password> -host <host> -port <port> -dir <remote dir> -file <filename>"
	echo
	echo "Parameter:"
	echo " -user: username"
	echo " -pwd : password. if password contains '!', wrap with single quotation."
	echo " -host: ssh host or domain name"
	echo " -port: ssh port"
	echo " -dir : remote directory to install files"
	echo " -file: filename"
}


while [ ! -z "$1" ];
do
	case "$1" in
		-user | --username)
			shift
			username="$1"
			;;
		-pwd | --password)
			shift
			password="$1"
			;;
		-host)
			shift
			host="$1"
			;;
		-port)
			shift
			port="$1"
			;;
		-dir)
			shift
			dir="$1"
			;;
		-file)
			shift
			filename="$1"
			;;
		-help)
			help
			exit 0
			;;
	*)
			;;
	esac
	shift
done

echo
args=("$username" "$password" "$host" "$port" "$filename" "$dir")
idx=0
for arg in "${args[@]}"
do
	if [ -z "$arg" ];
	then
		help "arguments is empy."
		exit 1
	fi
	((idx++))
done

FILENAME="$HOME/bin/$filename"
if [ -d $FILENAME ];
then
	help "$FILENAME is not valid. It is a directory."
	exit 1
fi

if [ -f $FILENAME ];
then
	read -p "*** '$FILENAME' already exists. Overwrite ? (Y/N) " confirm
	confirm=$(echo $confirm | tr [:lower:] [:upper:])
	if [ "$confirm" != "Y" ];
	then
		exit 1
	fi
fi

echo "#!/usr/bin/env bash" > "$FILENAME"

echo "" >> "$FILENAME"

echo "USER_NAME=\"$username\"" >> "$FILENAME"
echo "PASSWD=\"$password\"" >> "$FILENAME"
echo "DATE=\$(date \"+%Y%m%d\")" >> "$FILENAME"

echo "" >> "$FILENAME"

echo "SRC_DIR=\"\$1\"" >> "$FILENAME"
echo "TARGET_IP=\"$host\"" >> "$FILENAME"
echo "TARGET_PORT=\"$port\"" >> "$FILENAME"
echo "TARGET_DIR=\"$dir/\${DATE}\"" >> "$FILENAME"

echo "" >> "$FILENAME"

echo "if [ -z \"\$SRC_DIR\" ] || [ ! -d \"\$SRC_DIR\" ];" >> "$FILENAME"
echo "then" >> "$FILENAME"
echo "    echo" >> "$FILENAME"
echo "    echo \"배포할 디렉토리가 올바르지 않습니다. 입력=\$SRC_DIR\"" >> "$FILENAME"
echo "    exit 1" >> "$FILENAME"
echo "fi" >> "$FILENAME"

echo "" >> "$FILENAME"

echo "scp-dir.sh -u \"\$USER_NAME\" -i \"\$PASSWD\" -h \"\$TARGET_IP\" -p \"\$TARGET_PORT\" -s \"\$SRC_DIR\" -d \"\$TARGET_DIR\"" >> "$FILENAME"

echo "" >> "$FILENAME"

echo "exit 0" >> "$FILENAME"

echo
echo "*** '$filename' was created at $HOME/bin"
echo
echo "*** chmod +x $FILENAME"
chmod +x $FILENAME

echo
echo "---------------------------------------------------------------------------------------------------------"
echo "---------------------------------------------------------------------------------------------------------"
cat $FILENAME
echo "---------------------------------------------------------------------------------------------------------"
echo "---------------------------------------------------------------------------------------------------------"

echo
exit 0

