#!/usr/bin/env bash

# get a filename
FILENAME=$(basename $0)

help(){
	if [ ! -z "$1" ];then
		local indent=10
		local formatl=" - %-"$indent"s: %s\n"
		local formatr=" - %"$indent"s: %s\n"
		echo
		echo "================================================================================"
		printf "$formatl" "filename" "$FILENAME"
		printf "$formatl" "line" "$2"
		printf "$formatl" "callstack"
		local idx=1
		for func in ${FUNCNAME[@]:1}
		do
		printf "$formatr" "["$idx"]" $func
		((idx++))
		done
		printf "$formatl" "cause" "$1"
		echo "================================================================================"
	fi
	echo
	echo "Usage:"
	echo "sendtoother <src> <dst>"
	echo
	echo "See 'scp' command"
	scp 
}


if [[ ! -f "$1" && ! -d "$1" ]] || [ -z "$2" ] ;then
	help "Invalid 'source' or 'destination'. src='$1', dst='$2'" $LINENO
	exit 1
fi

ACCOUNT="<dest.account>"
DST="<dst.ip-address>"

echo
echo " >>> password: <dest.password>"
echo " >>> scp $1 $ACCOUNT@$DST:$2"
{
	scp $1 $ACCOUNT@$DST:$2 2>/dev/null
}||{
	help "Errors..." $LINENO
	exit 1
}

exit 0 
