##
# 카탈로그는 정보는 'title', 'description', 'catalog_url' 정보를 갖습니다.
# 
# title: 카탈로그 대표 이름.
# description: 카탈로그에 포함된 패키지, 도구 등을 설명하는 내용. 이 정보를 통해서 사용자는 선택을 할 것으로 판단됨.
# catalog_url: 설치 정보가 있는 파일 경로
##
[DevOps]
title=기본 개발 환경(빌드/배포/운영)
description=git, temurin-jdk-25, maven-3.9.15 환경을 제공합니다.
catalog_url=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/env/catalogs/default-devops/configurations.properties

[3rd Party services]
title=3rd Party 서비스 설치 및 운영
description=temurin-jdk-25 환경을 제공합니다.
catalog_url=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/env/catalogs/3rdparty-op/configurations.properties

[관리도구 설치]
title=서버 관리도구 설치
description=사용자/그룹 권한, 네트워크, 보안 등 시스템 관리를 위한 도구를 제공합니다.
catalog_url=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/env/catalogs/manage-server/configurations.properties

[Let's Encrypt 인증서 설치 지원]
title=Let's Encrypt 인증서 설치 지원
description=Let's Encrypt 인증서 설치용 RSA 공개키 설치
catalog_url=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/env/catalogs/install-lets-encrpt-certificate/configuration.properties

[Gitlab Group/Project Clone 설치 지원]
title=Gitlab Group/Project Clone 설치 지원
description=Gitlab Group/Project Clone 스크립트 설치.
catalog_url=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/env/catalogs/gitlab/configuration.properties

