# `sudo` 로 실행시 '비밀번호'를 물어보지 않는 명령어
NO_PASSWORD_COMMANDS=/usr/bin/cat, /usr/bin/systemctl, /usr/bin/update-alternatives, /usr/bin/vi, /usr/bin/vim, /bin/ps, /bin/netstat
# 기본 설치 도구
DEFAULT_TOOLS=curl, git, net-tools, vim
# 'vim' 확장 도구
URL_VIM_CLI=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/sys/vim-cli
# 'vim-cli'의 bash completion 
URL_VIM_CLI_COMPLETION=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/sys/vim-cli.completion
# JDK 설치 스크립트
URL_JDK_INSTALLER=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/java/install-temurin-25-jdk.sh
# 여러 버전의 JDK가 설치된 환경에서 '기본 버전'을 설정
URL_UPDATE_JAVA_CONFIG=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/java/update-java-config
# 'maven' 설치 파일
URL_MAVEN_FILE=https://dlcdn.apache.org/maven/maven-3/3.9.15/binaries/apache-maven-3.9.15-bin.tar.gz
# 여러 버전의 'maven' 이 설치된 환경에서 '기본 버전'을 설정
URL_UPDATE_MVN_CONFIG=https://raw.githubusercontent.com/parkjunhong/shellscripts/refs/heads/main/maven/update-mvn-config
# RSA 기반의 ssh 접속을 위한 공개키
RSA_PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2mUlqLFWYVRfgyKT1+wmsY0Yr/wYEPs16zj1Cvy1/9o0ja7v4WQd+PM7Ha1qS4bDWI1TdtF8pwUmeJGR/UkQNS2tnzMCzdbpI9v7YbV+gR6btYaHLz6EThmNnR8qvXUb5muXBVb9Pf0lu4FfsjPnYZ4mEtMkiQrXUNKvFQEYpgZNewGmd+Mmbpj3LSWFOHGfbn5a+IlI2UemZnlvgTkrf+shGszwftiEeUmTo0El9tg5/LArK480HaWehTB+ndheUb/h05LtNP/oUA+8ZVkI7akEonKF/S+0o5BC6spOzP7iK4S+I7IUVIuoDWuhDLEV6xHYXH1cBEd3092x1YWkh ymtech for internal
